apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    env  : test
spec:
  selector:
    project: {{ .Release.Name }}    # Selecting PODS with those Labels
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : TCP
      port      : 3000
      targetPort: 8080 # Port on POD
  type: ClusterIP